import { createSlice } from "@reduxjs/toolkit";
import profile from "../../assets/header/profile.svg";
import propertiesIcon from "../../assets/sidebar/home.svg";
import FoodCourt from "../../assets/Properties/food_court.svg";
import Parking from "../../assets/Properties/parking.svg";

const initialState = {
  dataTable: [
    {
      id: 1,
      // name: "Mukesh Kumar",
      host_name: "Mukesh Kumar",
      vehicle: "TATA Nexon",
      num: "6e9d42dc-1a2f-11ee",
      num1: "Ether Enterprises",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      img: profile,
      Properties: 2,
      City: "Salem",
      Chargers: 2,
      email: "mukesh@gmail.com",
      phone_number: "8999999925",
      phone: "8999999925",
      wallet: "1000",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "mukesh@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      status: true,
      title: "Details",
      organization: "Loreum Ipsum",
      taxNumber: "07AAGFF2194N1Z1",
      gstNumber: "24AAACR5055K1ZD",
      // tax: "07AAGFF2194N1Z1",
      // gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      admin_num: "1234",
      bank: "2031*******",
      title1: "Properties",
      title2: "Amentities",
      img1: propertiesIcon,
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      pincode: "614616",
      state: "Tamil Nadu",
      country: "India",
      // ifsc_number: "248781821",
      ifsc_code: "248781821",
      bank_account: "2749191201209",
      // account: "2749191201209",
      propertyimg1: FoodCourt,
      propertyAmentities1: "Food Court",
      propertyimg2: Parking,
      propertyAmentities2: "Free Parking",
      chargerName: "Chotta Bheem",
      status1: "Completed",
      wallet_id: "92974c72ec16dc7345",
      credit: "20.00",
      date_day: "17 July 2023",
      bank_name: "Axis Bank",
    },
    {
      id: 2,
      name: "Vignesh Kumar",
      vehicle: "TATA Nexon",
      num: "6e9d42dc-1a2f-11ee",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      num1: "Ether Enterprises",
      img: profile,
      email: "vickey@gmail.com",
      phone: "8999999925",
      wallet: "400",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "vignesh@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      City: "Salem",
      Chargers: 2,
      Properties: 2,
      status: false,
      title: "Details",
      organization: "Loreum Ipsum",
      tax: "07AAGFF2194N1Z1",
      gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      bank: "2031*******",
      title1: "Properties",
      ifsc_number: "248781821",
      img1: propertiesIcon,
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      pincode: "614616",
      status1: "Initiated",
      state: "Tamil Nadu",
      country: "India",
      date_day: "08 January 2024",
      details1: [
        {
          id: 1,
          title: "Details",
          content: [
            {
              id: 1,
              subContent: "Host",
              subContent1: "Ether Enterprises",
            },
            {
              id: 2,
              subContent: "City",
              subContent1: "Salem",
            },
            {
              id: 3,
              subContent: "Organisation Type",
              subContent1: "Loreum Ipsum",
            },
          ],
        },
        {
          id: 2,
          title: "Amenities",
          content: [
            {
              id: 1,
              img: propertiesIcon,
              subContent: "Windsor Castle ",
            },
            {
              id: 2,
              img: propertiesIcon,
              subContent: "Property 2 Salem",
            },
          ],
        },
      ],
    },
    {
      id: 3,
      name: "Kishore Kumar",
      vehicle: "TATA Nexon",
      num: "6e9d42dc-1a2f-11ee",
      num1: "Ether Enterprises",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      img: profile,
      email: "kishore@gmail.com",
      phone: "8999999925",
      wallet: "2564",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "kishore@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      City: "Salem",
      Chargers: 2,
      Properties: 2,
      status: false,
      title: "Details",
      organization: "Loreum Ipsum",
      tax: "07AAGFF2194N1Z1",
      gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      bank: "2031*******",
      title1: "Properties",
      ifsc_number: "248781821",
      img1: propertiesIcon,
      status1: "Suspended",
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      pincode: "614616",
      state: "Tamil Nadu",
      country: "India",
      date_day: "17 January 2024",
      details1: [
        {
          id: 1,
          title: "Details",
          content: [
            {
              id: 1,
              subContent: "Host",
              subContent1: "Ether Enterprises",
            },
            {
              id: 2,
              subContent: "City",
              subContent1: "Salem",
            },
            {
              id: 3,
              subContent: "Organisation Type",
              subContent1: "Loreum Ipsum",
            },
          ],
        },
        {
          id: 2,
          title: "Amenities",
          content: [
            {
              id: 1,
              img: propertiesIcon,
              subContent: "Windsor Castle ",
            },
            {
              id: 2,
              img: propertiesIcon,
              subContent: "Property 2 Salem",
            },
          ],
        },
      ],
    },
    {
      id: 4,
      name: "Kishore Kumar",
      vehicle: "TATA Nexon",
      num: "6e9d42dc-1a2f-11ee",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      num1: "Ether Enterprises",
      img: profile,
      email: "kishore@gmail.com",
      phone: "8999999925",
      wallet: "2564",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "kishore@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      City: "Salem",
      Chargers: 2,
      Properties: 2,
      status: false,
      title: "Details",
      organization: "Loreum Ipsum",
      tax: "07AAGFF2194N1Z1",
      gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      bank: "2031*******",
      title1: "Properties",
      img1: propertiesIcon,
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      ifsc_number: "248781821",
      pincode: "614616",
      status1: "Cancelled",
      state: "Tamil Nadu",
      country: "India",
      date_day: "17 July 2024",
      details1: [
        {
          id: 1,
          title: "Details",
          content: [
            {
              id: 1,
              subContent: "Host",
              subContent1: "Ether Enterprises",
            },
            {
              id: 2,
              subContent: "City",
              subContent1: "Salem",
            },
            {
              id: 3,
              subContent: "Organisation Type",
              subContent1: "Loreum Ipsum",
            },
          ],
        },
        {
          id: 2,
          title: "Amenities",
          content: [
            {
              id: 1,
              img: propertiesIcon,
              subContent: "Windsor Castle ",
            },
            {
              id: 2,
              img: propertiesIcon,
              subContent: "Property 2 Salem",
            },
          ],
        },
      ],
    },
    {
      id: 5,
      name: "Kishore Kumar",
      vehicle: "TATA Nexon",
      num: "6e9d42dc-1a2f-11ee",
      num1: "Ether Enterprises",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      City: "Salem",
      Chargers: 2,
      img: profile,
      email: "kishore@gmail.com",
      phone: "8999999925",
      wallet: "2564",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "kishore@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      Properties: 2,
      status: false,
      title: "Details",
      organization: "Loreum Ipsum",
      tax: "07AAGFF2194N1Z1",
      gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      bank: "2031*******",
      title1: "Properties",
      img1: propertiesIcon,
      ifsc_number: "248781821",
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      pincode: "614616",
      state: "Tamil Nadu",
      status1: "Interrupted",
      country: "India",
      date_day: "11 January 2024",
      details1: [
        {
          id: 1,
          title: "Details",
          content: [
            {
              id: 1,
              subContent: "Host",
              subContent1: "Ether Enterprises",
            },
            {
              id: 2,
              subContent: "City",
              subContent1: "Salem",
            },
            {
              id: 3,
              subContent: "Organisation Type",
              subContent1: "Loreum Ipsum",
            },
          ],
        },
        {
          id: 2,
          title: "Amenities",
          content: [
            {
              id: 1,
              img: propertiesIcon,
              subContent: "Windsor Castle ",
            },
            {
              id: 2,
              img: propertiesIcon,
              subContent: "Property 2 Salem",
            },
          ],
        },
      ],
    },
    {
      id: 6,
      name: "Kishore Kumar",
      vehicle: "TATA Nexon",
      num: "6e9d42dc-1a2f-11ee",
      num1: "Ether Enterprises",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      City: "Salem",
      Chargers: 2,
      img: profile,
      email: "kishore@gmail.com",
      phone: "8999999925",
      wallet: "2564",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "kishore@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      status: false,
      Properties: 2,
      title: "Details",
      organization: "Loreum Ipsum",
      tax: "07AAGFF2194N1Z1",
      gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      bank: "2031*******",
      title1: "Properties",
      ifsc_number: "248781821",
      img1: propertiesIcon,
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      pincode: "614616",
      state: "Tamil Nadu",
      country: "India",
      details1: [
        {
          id: 1,
          title: "Details",
          content: [
            {
              id: 1,
              subContent: "Host",
              subContent1: "Ether Enterprises",
            },
            {
              id: 2,
              subContent: "City",
              subContent1: "Salem",
            },
            {
              id: 3,
              subContent: "Organisation Type",
              subContent1: "Loreum Ipsum",
            },
          ],
        },
        {
          id: 2,
          title: "Amenities",
          content: [
            {
              id: 1,
              img: propertiesIcon,
              subContent: "Windsor Castle ",
            },
            {
              id: 2,
              img: propertiesIcon,
              subContent: "Property 2 Salem",
            },
          ],
        },
      ],
    },
    {
      id: 7,
      name: "Kishore Kumar",
      vehicle: "TATA Nexon",
      num: "6e9d42dc-1a2f-11ee",
      num1: "Ether Enterprises",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      img: profile,
      email: "kishore@gmail.com",
      phone: "8999999925",
      wallet: "2564",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "kishore@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      City: "Salem",
      Chargers: 2,
      Properties: 2,
      status: false,
      title: "Details",
      organization: "Loreum Ipsum",
      tax: "07AAGFF2194N1Z1",
      gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      bank: "2031*******",
      title1: "Properties",
      img1: propertiesIcon,
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      pincode: "614616",
      state: "Tamil Nadu",
      country: "India",
      details1: [
        {
          id: 1,
          title: "Details",
          content: [
            {
              id: 1,
              subContent: "Host",
              subContent1: "Ether Enterprises",
            },
            {
              id: 2,
              subContent: "City",
              subContent1: "Salem",
            },
            {
              id: 3,
              subContent: "Organisation Type",
              subContent1: "Loreum Ipsum",
            },
          ],
        },
        {
          id: 2,
          title: "Amenities",
          content: [
            {
              id: 1,
              img: propertiesIcon,
              subContent: "Windsor Castle ",
            },
            {
              id: 2,
              img: propertiesIcon,
              subContent: "Property 2 Salem",
            },
          ],
        },
      ],
    },
    {
      id: 8,
      name: "Kishore Kumar",
      vehicle: "TATA Nexon",
      num: "6e9d42dc-1a2f-11ee",
      num1: "Ether Enterprises",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      City: "Salem",
      Chargers: 2,
      img: profile,
      email: "kishore@gmail.com",
      phone: "8999999925",
      wallet: "2564",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "kishore@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      status: false,
      Properties: 2,
      title: "Details",
      organization: "Loreum Ipsum",
      tax: "07AAGFF2194N1Z1",
      gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      bank: "2031*******",
      title1: "Properties",
      img1: propertiesIcon,
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      pincode: "614616",
      state: "Tamil Nadu",
      country: "India",
      ifsc_code: "6383",
      details1: [
        {
          id: 1,
          title: "Details",
          content: [
            {
              id: 1,
              subContent: "Host",
              subContent1: "Ether Enterprises",
            },
            {
              id: 2,
              subContent: "City",
              subContent1: "Salem",
            },
            {
              id: 3,
              subContent: "Organisation Type",
              subContent1: "Loreum Ipsum",
            },
          ],
        },
        {
          id: 2,
          title: "Amenities",
          content: [
            {
              id: 1,
              img: propertiesIcon,
              subContent: "Windsor Castle ",
            },
            {
              id: 2,
              img: propertiesIcon,
              subContent: "Property 2 Salem",
            },
          ],
        },
      ],
    },
    {
      id: 9,
      name: "Kishore Kumar",
      vehicle: "TATA Nexon",
      num: "6e9d42dc-1a2f-11ee",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      num1: "Ether Enterprises",
      img: profile,
      email: "kishore@gmail.com",
      phone: "8999999925",
      wallet: "2564",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "kishore@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      status: false,
      City: "Salem",
      Chargers: 2,
      Properties: 2,
      title: "Details",
      organization: "Loreum Ipsum",
      tax: "07AAGFF2194N1Z1",
      gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      bank: "2031*******",
      title1: "Properties",
      img1: propertiesIcon,
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      pincode: "614616",
      state: "Tamil Nadu",
      country: "India",
      details1: [
        {
          id: 1,
          title: "Details",
          content: [
            {
              id: 1,
              subContent: "Host",
              subContent1: "Ether Enterprises",
            },
            {
              id: 2,
              subContent: "City",
              subContent1: "Salem",
            },
            {
              id: 3,
              subContent: "Organisation Type",
              subContent1: "Loreum Ipsum",
            },
          ],
        },
        {
          id: 2,
          title: "Amenities",
          content: [
            {
              id: 1,
              img: propertiesIcon,
              subContent: "Windsor Castle ",
            },
            {
              id: 2,
              img: propertiesIcon,
              subContent: "Property 2 Salem",
            },
          ],
        },
      ],
    },
    {
      id: 10,
      name: "Kishore Kumar",
      vehicle: "TATA Nexon",
      text: " Lorem ipsum dolor sit amet consectetur. Non nec id mauris fames vitae.Faucibus rutrum vestibulum vulputate nisl sed orci quam.",
      num: "6e9d42dc-1a2f-11ee",
      num1: "Ether Enterprises",
      City: "Salem",
      Chargers: 2,
      img: profile,
      email: "kishore@gmail.com",
      phone: "8999999925",
      wallet: "2564",
      address: "No 9, 22/1, Os Nagar Salem",
      mail: "kishore@gmail.com",
      date: "12:30 PM",
      time: "31 Jan",
      status: false,
      Properties: 2,
      title: "Details",
      organization: "Loreum Ipsum",
      tax: "07AAGFF2194N1Z1",
      gst: "24AAACR5055K1ZD",
      admin: "admin@etherenterprises.com",
      bank: "2031*******",
      title1: "Properties",
      img1: propertiesIcon,
      // property1: "Windsor Castle ",
      property2: "Property 2 Salem",
      pincode: "614616",
      state: "Tamil Nadu",
      country: "India",
      details1: [
        {
          id: 1,
          title: "Details",
          content: [
            {
              id: 1,
              subContent: "Host",
              subContent1: "Ether Enterprises",
            },
            {
              id: 2,
              subContent: "City",
              subContent1: "Salem",
            },
            {
              id: 3,
              subContent: "Organisation Type",
              subContent1: "Loreum Ipsum",
            },
          ],
        },
        {
          id: 2,
          title: "Amenities",
          content: [
            {
              id: 1,
              img: propertiesIcon,
              subContent: "Windsor Castle ",
            },
            {
              id: 2,
              img: propertiesIcon,
              subContent: "Property 2 Salem",
            },
          ],
        },
      ],
    },
  ],

  options: {
    organization: [
      {
        id: 1,
        value: "pudukkottai",
      },
      {
        id: 2,
        value: "trichy",
      },
      {
        id: 3,
        value: "madurai",
      },
    ],
    City: [
      { id: 1, value: "city1" },
      { id: 2, value: "city2" },
      { id: 3, value: "city3" },
    ],
    state: [
      { id: 1, value: "state1" },
      { id: 2, value: "state2" },
      { id: 3, value: "state3" },
    ],
    country: [
      { id: 1, value: "country1" },
      { id: 2, value: "country2" },
      { id: 3, value: "country3" },
    ],
  },

  // currentData: {},
};

const tableSlice = createSlice({
  name: "dataTable",
  initialState,

  reducers: {
    setDataTable(state, action) {
      state.dataTable = action.payload;
    },

    // setCurrentData(state, action) {
    //   state.currentData = state.dataTable.find(
    //     (data) => data.id == action.payload
    //   );
    // },
    update: (state, action) => {
      const { id, currentData } = action.payload;
      // console.log(action);
      const res = state.dataTable.map((data) => {
        if (data.id === id) {
          return currentData;
        } else {
          return data;
        }
      });
      // console.log(res);
      state.dataTable = res;
    },
  },
});

export const { setDataTable, update } = tableSlice.actions;
export default tableSlice.reducer;
