version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/app
    container_name: helios
    expose:
      - 8080
    ports:
      - 8080:8080
    command: npm run dev
